---
- hosts: master_nodes
  become: true
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="192.168.1.9" --apiserver-cert-extra-sans="192.168.1.9"  --node-name=k8s-master --pod-network-cidr=192.168.1.0/24
